config/routes.rb
Rails.application.routes.draw do
  resources :clickcounts, only: %i[ index create destroy ] 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/*
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "clickcounts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/clickcount.rb
class Clickcount < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

app/controllers/clickcounts_controller.rb
class ClickcountsController < ApplicationController
  def index
    @count = Clickcount.find_by(id: 1)
  end

  def create
    @count = Clickcount.find_or_create_by(id: 1)
    @count.increment!(:count)
    @count.broadcast_update_to("counts", target: "all_click_count", locals: { count: @count })
  end

  def destroy
    @count = Clickcount.find_or_create_by(id: 1)
    @count.update!(count: 0)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clickcounts_helper.rb
module ClickcountsHelper
end

app/views/clickcounts/_clickcount.html.erb
<p class="text-6xl mt-6"><%= count.count %></p>

app/views/clickcounts/_reset_button.html.erb
<%= form_with url: clickcount_path(id: 1), method: :delete do |f| %>
  <%= f.submit "リセット", 
      class: "my-12 group relative inline-flex h-12 items-center justify-center overflow-hidden
              rounded-md  bg-[#A8D5BA] hover:bg-[#95CBAF] hover:[box-shadow:0px_4px_1px_#69B37B] 
              px-10 font-medium text-white  transition-all [box-shadow:0px_4px_1px_#81C784] 
              active:translate-y-[2px] active:shadow-none" %>
<% end %>

app/views/clickcounts/_session_count.html.erb
<p class="text-3xl mt-6" id="session_click_count"></p>

app/views/clickcounts/index.html.erb
<%= turbo_stream_from "counts" %>

<header>
</header>

<main class="max-w-2xs mx-auto text-center my-40 max-sm:mt-16 max-sm:mb-20">
  <div class="text-center">
    <p class="text-3xl max-sm:text-2xl">らんぱすー</p>
    <p class="text-6xl mt-6 font-normal", id="all_click_count"><%= @count&.count %></p>
  </div>

  <%= audio_tag "/runpath.wav", id: "audio-play" %>

  <%= form_with url: clickcounts_path, method: :post, local: false, data: { turbo_method: :post } do |f| %>
    <%= f.submit 'らんぱすー', id: "audio-btn", 
        class: "mt-12 mb-6 group relative inline-flex h-12 items-center justify-center overflow-hidden 
                rounded-md bg-[#f09134] hover:bg-[#F4A261] hover:[box-shadow:0px_4px_1px_#E76F51] 
                p-10 max-sm:p-8 font-medium text-white text-3xl max-sm:text-2xl leading-0 transition-all 
                [box-shadow:0px_4px_1px_#E76F51] active:translate-y-[2px] active:shadow-none" %>
  <% end %>
  
  <div id="volume-loud" class="mt-2" >
    <%= image_tag 'volume-loud.svg', class: 'mx-auto' %>
  </div>
  <div id="volume-mute", class="hidden mt-2">
    <%= image_tag 'volume-mute.svg', class: 'mx-auto'  %>
  </div>

  <%# <%= render 'reset_button' %> 

  <div class="mt-10">
    <div class="text-center">
      <P>あなたの&nbsp;らんぱすー</p>
      <p class="text-3xl mt-2 font-normal", id="session_click_count">0</p>
      <button type='button' id='session-update-button' class='bg-[#8abea3] hover:bg-[#a3cca9] hover:[box-shadow:0px_4px_1px_#81C784] text-white font-medium py-2 px-4 overflow-hidden rounded-md mt-4 transition-all [box-shadow:0px_4px_1px_#6DA98A] active:translate-y-[2px] active:shadow-none'>
        りろーど
      </button>
    </div>

    <div class="my-12">
      <button type='button' id='x-post-button' class="text-black bg-[#AEDFF7] hover:bg-[#AEDFF7]/80   font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center ">
        <%= image_tag 'x-twitter-brands.svg',width: '20px' %><p>&emsp;しぇあ</p>
      </button>
    </div>
    <%# 隠しボタン %>
    <div class="my-12 hidden" id="secret-button">
      <button type='button' id='secret-x-post-button' class="text-black bg-[#AEDFF7] hover:bg-[#AEDFF7]/80   font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center ">
        <%= image_tag 'x-twitter-brands.svg',width: '20px' %><p>&emsp;かくししぇあ</p>
      </button>
    </div>
  </div>
  
</main>

<footer>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="charset=UTF-8" />
    <%# XのOGP %>
    <meta property="og:title" content="らんぱすーぼたん" />
    <meta property="og:description" content="らんぱすー" />
    <meta property="og:image" content="https://runpath.onrender.com/run_path.png" />
    <meta property="og:url" content="https://runpath.onrender.com/" />
    <meta property="og:type" content="website" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="らんぱすーぼたん" />
    <meta name="twitter:description" content="らんぱすー" />
    <%#  %>
    <title><%= content_for(:title) || "らんぱすーぼたん" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <script>
      window.secretCommand = "<%= Rails.application.credentials.dig(:secret, :code) %>".split(",");
    </script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
        <%# favicon設定 %>
    <link rel="manifest" href="/manifest.json" />
    <link rel="icon" href="/run_path.png" type="image/png" />
    <link rel="icon" href="/run_path.svg" type="image/svg+xml" />
    <link rel="apple-touch-icon" href="/runpath.png" />
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>
  <body class="bg-yellow-50">
    <%# <main class="container mx-auto mt-28 px-5 flex"> %>
    <%= yield %>
    <%# </main> %>
  </body>
</html>